spring:
  datasource:
    # 환경변수 또는 직접 입력 (예: username: root, password: yourpassword)
    url: jdbc:mysql://localhost:3306/bcsd?serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
